var LANG = {

  en: {
    // NAV
    nav_home:"Home", nav_services:"Services", nav_destinations:"Destinations",
    nav_process:"Process", nav_about:"About", nav_blog:"Blog", nav_contact:"Contact",
    nav_cta:"Private Consultation",

    // HOME
    hero_eyebrow:"International Medical Concierge",
    hero_h1_1:"Access the World's", hero_h1_2:"Finest Medical", hero_h1_3:"Expertise",
    hero_p:"We connect distinguished international patients with the most advanced medical institutions in Europe — handling every detail from specialist appointments to private travel arrangements.",
    hero_btn:"Request a Private Consultation", hero_btn2:"How it works",
    badge1:"Absolute Confidentiality", badge2:"24/7 Dedicated Support", badge3:"Multilingual Assistance",
    stat1_label:"Average response time", stat2_label:"Partner institutions",
    stat3_label:"Medical destinations", stat4_label:"Confidential service",
    overview_tag:"What We Offer",
    overview_h2_1:"Everything You Need,", overview_h2_2:"Perfectly Orchestrated",
    ov1_title:"Medical Coordination", ov1_text:"Expert analysis of your medical file and direct access to world-leading specialists across every discipline.", ov1_link:"Discover our services →",
    ov2_title:"Premier Destinations", ov2_text:"Paris, Geneva, London, Berlin — the four capitals of medical excellence in Europe, accessible to you.", ov2_link:"View destinations →",
    ov3_title:"Seamless Process", ov3_text:"From your first contact to full recovery, a dedicated concierge manages every step of your journey.", ov3_link:"How it works →",
    cta_h2_1:"Your health cannot wait.", cta_h2_2:"Neither can we.",
    cta_p:"Our team responds within 48 hours to every inquiry, with absolute discretion and professional care.",
    cta_btn:"Request a Private Consultation",
    gal1:"VIP Hospitality", gal2:"Paris, France", gal3:"European Excellence", gal4:"Private Travel",
    footer_copy:"© 2025 NobleCare. All rights reserved.",

    // SERVICES PAGE
    svc_eyebrow:"Our Services",
    svc_h1_1:"A Complete Suite of", svc_h1_2:"Premium Medical Services",
    svc_tag:"What We Offer",
    svc_h2_1:"Every Aspect of Your Journey,", svc_h2_2:"Perfectly Managed",
    svc_sub:"From your first contact to full recovery, our team orchestrates each detail with precision and discretion.",
    svc1_title:"Medical Coordination", svc1_desc:"Expert analysis of your medical file and direct access to world-leading specialists across every discipline. We identify the right institution and the right expert for your exact condition.",
    svc1_l1:"Comprehensive medical file evaluation", svc1_l2:"Identification of optimal hospital & specialist", svc1_l3:"Priority appointment scheduling", svc1_l4:"Oncology, cardiology & rare diseases", svc1_l5:"Second opinion services", svc1_l6:"Treatment plan coordination",
    svc2_title:"Travel & Logistics", svc2_desc:"Seamless international travel arrangements including medical visa procurement, private aviation coordination, and premium accommodation — so your focus remains entirely on your health.",
    svc2_l1:"Medical visa procurement & assistance", svc2_l2:"Private jet & business class coordination", svc2_l3:"5-star hotel & hospital suite booking", svc2_l4:"Private airport transfers", svc2_l5:"Family accommodation arrangements", svc2_l6:"Return journey planning",
    svc3_title:"Personal Assistance", svc3_desc:"A dedicated personal assistant accompanies you throughout your entire medical journey, ensuring clear communication and seamless coordination at every step.",
    svc3_l1:"Certified medical interpreters (EN / FR / AR)", svc3_l2:"24h dedicated personal assistant", svc3_l3:"Hospital accompaniment & liaison", svc3_l4:"Administrative & paperwork support", svc3_l5:"Family communication & updates", svc3_l6:"Post-consultation follow-up",
    svc4_title:"VIP Services", svc4_desc:"The highest standard of private care and security for clients who require complete discretion and an uncompromising level of personal comfort.",
    svc4_l1:"Private security detail", svc4_l2:"Premium hospital suites & private rooms", svc4_l3:"Private chef if required", svc4_l4:"Luxury post-operative care arrangements", svc4_l5:"Companion & family concierge services", svc4_l6:"Confidential communications management",
    price_tag:"Concierge Fee", price_h2_1:"Transparent,", price_h2_2:"All-Inclusive Pricing",
    price_label:"Base Concierge Fee", price_period:"per case — excluding medical & travel costs",
    price_desc:"Our concierge fee covers the full coordination service: medical file analysis, specialist identification, appointment scheduling, and logistical management. Medical treatment costs, travel, and accommodation are billed separately and transparently.",
    price_btn:"Request a Detailed Quote",

    // DESTINATIONS PAGE
    dest_eyebrow:"Medical Destinations",
    dest_h1_1:"Europe's Premier", dest_h1_2:"Medical Cities",
    dest_tag:"4 Destinations",
    dest_h2_1:"The World's Most Advanced", dest_h2_2:"Medical Centres",
    dest_sub:"We partner exclusively with the highest-ranked institutions in Europe, selected for clinical excellence, research innovation, and experience with international patients.",
    dest_cta_tag:"Not Sure Which Destination?",
    dest_cta_h2_1:"We Will Recommend", dest_cta_h2_2:"The Right Choice",
    dest_cta_p:"Share your medical situation and we will identify the hospital and city best suited to your condition.",
    dest_cta_btn:"Get a Recommendation",

    // PROCESS PAGE
    proc_eyebrow:"How It Works",
    proc_h1_1:"Your Journey in", proc_h1_2:"Five Steps",
    proc_tag:"The NobleCare Process",
    proc_h2_1:"From First Contact", proc_h2_2:"to Full Recovery",
    proc_sub:"We manage every aspect of your medical journey so that you and your family can focus on what matters most — your health.",
    step1_tag:"Initial Contact", step1_title:"You Reach Out",
    step1_desc:"The process begins the moment you contact us — by phone, WhatsApp, email, or our secure form. You will be assigned a dedicated case manager within 24 hours.",
    step2_tag:"Medical Review", step2_title:"We Analyse Your Case",
    step2_desc:"Your medical file is reviewed by our network of partner specialists. We assess all treatment options, identify the most appropriate institution, and estimate realistic timelines.",
    step3_tag:"Personalised Proposal", step3_title:"Your Complete Plan",
    step3_desc:"We present you with a comprehensive, fully itemised plan covering the recommended hospital, specialist, treatment pathway, travel schedule, accommodation, and complete cost estimate.",
    step4_tag:"Full Organisation", step4_title:"We Handle Everything",
    step4_desc:"Upon your approval, we manage the entire logistical operation: medical visa, international flights, private transfers, hotel or hospital suite booking, and confirmation of all medical appointments.",
    step5_tag:"On-Site Accompaniment", step5_title:"We Are With You",
    step5_desc:"From the moment you land, your personal concierge is at your side. We escort you through every appointment, translate every consultation, and manage every administrative detail.",
    proc_ready_tag:"Ready to Begin?",
    proc_ready_h2_1:"Start Your Journey", proc_ready_h2_2:"Today",
    proc_ready_p:"Submit your medical file securely and receive your personalised treatment plan within 48 hours.",
    proc_ready_btn1:"Request a Consultation", proc_ready_btn2:"View Our Services",

    // ABOUT PAGE
    about_eyebrow:"About NobleCare",
    about_h1_1:"Trusted by the World's", about_h1_2:"Most Discerning Families",
    about_mission_tag:"Our Mission",
    about_mission_h2_1:"When Health Cannot Wait,", about_mission_h2_2:"Every Detail Matters",
    about_p1:"NobleCare was founded on a simple but powerful conviction: that access to the world's finest medical care should never be limited by geography, administration, or complexity.",
    about_pull:"\"We bridge the distance between your family and the best specialists on the planet.\"",
    about_p2:"We act as a trusted intermediary — part medical coordinator, part travel expert, part personal advisor — guiding our clients through every step of an international medical journey with precision, warmth, and absolute discretion.",
    about_values_tag:"Our Values",
    about_values_h2_1:"The Principles That", about_values_h2_2:"Guide Everything We Do",
    val1_title:"Excellence Without Compromise", val1_text:"We partner exclusively with institutions ranked among the world's finest.",
    val2_title:"Absolute Confidentiality", val2_text:"Every case is handled under strict non-disclosure.",
    val3_title:"Genuine Human Care", val3_text:"Behind every case is a family facing uncertainty. We approach every client with warmth and empathy.",
    testi_tag:"Client Testimonials",
    testi_h2_1:"Words from Those", testi_h2_2:"We Have Served",

    // CONTACT PAGE
    contact_eyebrow:"Contact Us",
    contact_h1_1:"Request a", contact_h1_2:"Private Consultation",
    contact_tag:"Get in Touch",
    contact_h2_1:"We Are Here", contact_h2_2:"For You",
    contact_p1:"All inquiries are handled with absolute discretion. Our team will respond within 48 hours to discuss your situation and how we can best assist you and your family.",
    contact_p2:"Whether you have an urgent medical need or are simply exploring options, there is no obligation. Your first consultation is entirely confidential and free of charge.",
    contact_email_label:"Secure Email", contact_wa_label:"WhatsApp", contact_phone_label:"Private Line",
    form_title:"Private Consultation Request",
    form_sub:"All information is treated in strict confidence.",
    form_lock:"🔒 Your data is never shared with third parties.",
    form_fname:"First Name *", form_lname:"Last Name *",
    form_email:"Email Address *", form_phone:"Phone / WhatsApp",
    form_country:"Country of Residence *", form_country_default:"Select your country",
    form_specialty:"Medical Specialty Required *", form_specialty_default:"Select a specialty",
    form_dest:"Preferred Destination", form_dest_default:"No preference — recommend the best",
    form_message:"Brief Description",
    form_submit:"Submit Consultation Request →",

    // BLOG
    blog_eyebrow:"Medical Insights",
    blog_h1_1:"Expert Guides for", blog_h1_2:"International Patients",
    blog_tag:"All Articles",
    newsletter_h2_1:"Stay", newsletter_h2_2:"Informed",
    newsletter_p:"Receive our expert guides on medical travel, European healthcare, and patient rights — delivered discreetly to your inbox.",
    newsletter_btn:"Subscribe",
  },

  fr: {
    nav_home:"Accueil", nav_services:"Services", nav_destinations:"Destinations",
    nav_process:"Processus", nav_about:"À propos", nav_blog:"Blog", nav_contact:"Contact",
    nav_cta:"Consultation Privée",
    hero_eyebrow:"Conciergerie Médicale Internationale",
    hero_h1_1:"Accédez aux Meilleurs", hero_h1_2:"Experts Médicaux", hero_h1_3:"du Monde",
    hero_p:"Nous mettons en relation des patients internationaux de haut standing avec les institutions médicales les plus avancées d'Europe — en gérant chaque détail, des rendez-vous spécialisés aux arrangements de voyage privé.",
    hero_btn:"Demander une Consultation Privée", hero_btn2:"Comment ça marche",
    badge1:"Confidentialité Absolue", badge2:"Support Dédié 24h/24", badge3:"Assistance Multilingue",
    stat1_label:"Temps de réponse moyen", stat2_label:"Institutions partenaires",
    stat3_label:"Destinations médicales", stat4_label:"Service confidentiel",
    overview_tag:"Nos Offres",
    overview_h2_1:"Tout ce dont vous avez besoin,", overview_h2_2:"Parfaitement Orchestré",
    ov1_title:"Coordination Médicale", ov1_text:"Analyse experte de votre dossier et accès direct aux meilleurs spécialistes mondiaux.", ov1_link:"Découvrir nos services →",
    ov2_title:"Destinations Phares", ov2_text:"Paris, Genève, Londres, Berlin — les quatre capitales de l'excellence médicale en Europe.", ov2_link:"Voir les destinations →",
    ov3_title:"Processus Fluide", ov3_text:"Du premier contact jusqu'à la guérison complète, un concierge dédié gère chaque étape.", ov3_link:"Comment ça marche →",
    cta_h2_1:"Votre santé n'attend pas.", cta_h2_2:"Nous non plus.",
    cta_p:"Notre équipe répond sous 48 heures à chaque demande, avec une discrétion absolue et un soin professionnel.",
    cta_btn:"Demander une Consultation Privée",
    gal1:"Hospitalité VIP", gal2:"Paris, France", gal3:"Excellence Européenne", gal4:"Voyage Privé",
    footer_copy:"© 2025 NobleCare. Tous droits réservés.",
    svc_eyebrow:"Nos Services",
    svc_h1_1:"Une Suite Complète de", svc_h1_2:"Services Médicaux Premium",
    svc_tag:"Ce Que Nous Offrons",
    svc_h2_1:"Chaque Aspect de Votre Parcours,", svc_h2_2:"Parfaitement Géré",
    svc_sub:"Du premier contact jusqu'à la guérison, notre équipe orchestre chaque détail avec précision et discrétion.",
    svc1_title:"Coordination Médicale", svc1_desc:"Analyse experte de votre dossier médical et accès direct aux meilleurs spécialistes mondiaux. Nous identifions l'institution et l'expert adaptés à votre condition.",
    svc1_l1:"Évaluation complète du dossier médical", svc1_l2:"Identification de l'hôpital et du spécialiste optimal", svc1_l3:"Prise de rendez-vous prioritaire", svc1_l4:"Oncologie, cardiologie & maladies rares", svc1_l5:"Services de deuxième avis", svc1_l6:"Coordination du plan de traitement",
    svc2_title:"Voyage & Logistique", svc2_desc:"Organisation complète du voyage international incluant l'obtention du visa médical, la coordination de l'aviation privée et l'hébergement haut de gamme.",
    svc2_l1:"Obtention du visa médical", svc2_l2:"Coordination jet privé & classe affaires", svc2_l3:"Réservation hôtel 5 étoiles & suite hospitalière", svc2_l4:"Transferts privés aéroport", svc2_l5:"Hébergement pour la famille", svc2_l6:"Organisation du voyage de retour",
    svc3_title:"Assistance Personnelle", svc3_desc:"Un assistant personnel dédié vous accompagne tout au long de votre parcours médical, assurant une communication claire à chaque étape.",
    svc3_l1:"Interprètes médicaux certifiés (EN / FR / AR)", svc3_l2:"Assistant personnel dédié 24h/24", svc3_l3:"Accompagnement et liaison hospitalière", svc3_l4:"Soutien administratif", svc3_l5:"Communication et mises à jour pour la famille", svc3_l6:"Suivi post-consultation",
    svc4_title:"Services VIP", svc4_desc:"Le plus haut standard de soins privés et de sécurité pour les clients qui exigent une discrétion totale et un niveau de confort personnel incomparable.",
    svc4_l1:"Sécurité privée", svc4_l2:"Suites hospitalières premium", svc4_l3:"Chef privé si nécessaire", svc4_l4:"Soins post-opératoires de luxe", svc4_l5:"Services de conciergerie famille", svc4_l6:"Gestion confidentielle des communications",
    price_tag:"Frais de Conciergerie", price_h2_1:"Tarification Transparente,", price_h2_2:"Tout Compris",
    price_label:"Frais de Base", price_period:"par dossier — hors frais médicaux et de voyage",
    price_desc:"Nos frais de conciergerie couvrent l'intégralité du service de coordination : analyse du dossier médical, identification du spécialiste, prise de rendez-vous et gestion logistique.",
    price_btn:"Demander un Devis Détaillé",
    dest_eyebrow:"Destinations Médicales",
    dest_h1_1:"Les Premières Villes", dest_h1_2:"Médicales d'Europe",
    dest_tag:"4 Destinations",
    dest_h2_1:"Les Centres Médicaux", dest_h2_2:"les Plus Avancés du Monde",
    dest_sub:"Nous collaborons exclusivement avec les institutions les mieux classées d'Europe, sélectionnées pour leur excellence clinique et leur expérience avec les patients internationaux.",
    dest_cta_tag:"Pas sûr de la destination ?",
    dest_cta_h2_1:"Nous Recommanderons", dest_cta_h2_2:"Le Bon Choix",
    dest_cta_p:"Partagez votre situation médicale et nous identifierons l'hôpital et la ville les mieux adaptés à votre condition.",
    dest_cta_btn:"Obtenir une Recommandation",
    proc_eyebrow:"Comment Ça Marche",
    proc_h1_1:"Votre Parcours en", proc_h1_2:"Cinq Étapes",
    proc_tag:"Le Processus NobleCare",
    proc_h2_1:"Du Premier Contact", proc_h2_2:"à la Guérison Complète",
    proc_sub:"Nous gérons chaque aspect de votre parcours médical afin que vous et votre famille puissiez vous concentrer sur ce qui compte le plus — votre santé.",
    step1_tag:"Contact Initial", step1_title:"Vous Nous Contactez",
    step1_desc:"Le processus commence dès que vous nous contactez — par téléphone, WhatsApp, email ou notre formulaire sécurisé. Un gestionnaire de dossier dédié vous sera attribué sous 24 heures.",
    step2_tag:"Analyse Médicale", step2_title:"Nous Analysons Votre Dossier",
    step2_desc:"Votre dossier médical est examiné par notre réseau de spécialistes partenaires. Nous évaluons toutes les options de traitement et identifions l'institution la plus appropriée.",
    step3_tag:"Proposition Personnalisée", step3_title:"Votre Plan Complet",
    step3_desc:"Nous vous présentons un plan complet et détaillé couvrant l'hôpital recommandé, le spécialiste, le parcours de traitement, le calendrier de voyage et l'estimation des coûts.",
    step4_tag:"Organisation Complète", step4_title:"Nous Gérons Tout",
    step4_desc:"Après votre accord, nous gérons l'intégralité de l'opération logistique : visa médical, vols internationaux, transferts privés et réservation de l'hébergement.",
    step5_tag:"Accompagnement Sur Place", step5_title:"Nous Sommes à Vos Côtés",
    step5_desc:"Dès votre arrivée, votre concierge personnel est à vos côtés. Nous vous accompagnons à chaque rendez-vous, traduisons chaque consultation et gérons chaque détail administratif.",
    proc_ready_tag:"Prêt à Commencer ?",
    proc_ready_h2_1:"Démarrez Votre Parcours", proc_ready_h2_2:"Aujourd'hui",
    proc_ready_p:"Soumettez votre dossier médical en toute sécurité et recevez votre plan de traitement personnalisé sous 48 heures.",
    proc_ready_btn1:"Demander une Consultation", proc_ready_btn2:"Voir Nos Services",
    about_eyebrow:"À Propos de NobleCare",
    about_h1_1:"Choisi par les Familles", about_h1_2:"les Plus Exigeantes du Monde",
    about_mission_tag:"Notre Mission",
    about_mission_h2_1:"Quand la Santé N'attend Pas,", about_mission_h2_2:"Chaque Détail Compte",
    about_p1:"NobleCare a été fondé sur une conviction simple mais puissante : l'accès aux meilleurs soins médicaux mondiaux ne devrait jamais être limité par la géographie ou la complexité administrative.",
    about_pull:"\"Nous comblons la distance entre votre famille et les meilleurs spécialistes de la planète.\"",
    about_p2:"Nous agissons comme un intermédiaire de confiance — coordinateur médical, expert en voyage et conseiller personnel — guidant nos clients à chaque étape avec précision et discrétion absolue.",
    about_values_tag:"Nos Valeurs",
    about_values_h2_1:"Les Principes qui", about_values_h2_2:"Guident Tout ce que Nous Faisons",
    val1_title:"Excellence Sans Compromis", val1_text:"Nous collaborons exclusivement avec les institutions les mieux classées au monde.",
    val2_title:"Confidentialité Absolue", val2_text:"Chaque dossier est traité sous strict accord de non-divulgation.",
    val3_title:"Soin Humain Authentique", val3_text:"Derrière chaque dossier se trouve une famille face à l'incertitude. Nous approchons chaque client avec chaleur et empathie.",
    testi_tag:"Témoignages Clients",
    testi_h2_1:"Les Mots de Ceux", testi_h2_2:"que Nous Avons Servis",
    contact_eyebrow:"Contactez-Nous",
    contact_h1_1:"Demander une", contact_h1_2:"Consultation Privée",
    contact_tag:"Prenez Contact",
    contact_h2_1:"Nous Sommes", contact_h2_2:"Là Pour Vous",
    contact_p1:"Toutes les demandes sont traitées avec une discrétion absolue. Notre équipe répondra sous 48 heures pour discuter de votre situation.",
    contact_p2:"Que vous ayez un besoin médical urgent ou que vous exploriez simplement vos options, il n'y a aucune obligation. Votre première consultation est entièrement confidentielle et gratuite.",
    contact_email_label:"Email Sécurisé", contact_wa_label:"WhatsApp", contact_phone_label:"Ligne Privée",
    form_title:"Demande de Consultation Privée",
    form_sub:"Toutes les informations sont traitées en toute confidentialité.",
    form_lock:"🔒 Vos données ne sont jamais partagées avec des tiers.",
    form_fname:"Prénom *", form_lname:"Nom *",
    form_email:"Adresse Email *", form_phone:"Téléphone / WhatsApp",
    form_country:"Pays de Résidence *", form_country_default:"Sélectionnez votre pays",
    form_specialty:"Spécialité Médicale Requise *", form_specialty_default:"Sélectionnez une spécialité",
    form_dest:"Destination Préférée", form_dest_default:"Pas de préférence — recommandez le mieux",
    form_message:"Brève Description",
    form_submit:"Envoyer la Demande de Consultation →",
    blog_eyebrow:"Guides Médicaux",
    blog_h1_1:"Guides d'Experts pour", blog_h1_2:"Patients Internationaux",
    blog_tag:"Tous les Articles",
    newsletter_h2_1:"Restez", newsletter_h2_2:"Informé",
    newsletter_p:"Recevez nos guides experts sur le voyage médical, la santé européenne et les droits des patients — livrés discrètement dans votre boîte mail.",
    newsletter_btn:"S'abonner",
  },

  es: {
    nav_home:"Inicio", nav_services:"Servicios", nav_destinations:"Destinos",
    nav_process:"Proceso", nav_about:"Nosotros", nav_blog:"Blog", nav_contact:"Contacto",
    nav_cta:"Consulta Privada",
    hero_eyebrow:"Conserjería Médica Internacional",
    hero_h1_1:"Acceda a la Mejor", hero_h1_2:"Experiencia Médica", hero_h1_3:"del Mundo",
    hero_p:"Conectamos a pacientes internacionales distinguidos con las instituciones médicas más avanzadas de Europa, gestionando cada detalle desde citas con especialistas hasta arreglos de viaje privado.",
    hero_btn:"Solicitar una Consulta Privada", hero_btn2:"Cómo funciona",
    badge1:"Confidencialidad Absoluta", badge2:"Soporte Dedicado 24/7", badge3:"Asistencia Multilingüe",
    stat1_label:"Tiempo de respuesta promedio", stat2_label:"Instituciones asociadas",
    stat3_label:"Destinos médicos", stat4_label:"Servicio confidencial",
    overview_tag:"Lo Que Ofrecemos",
    overview_h2_1:"Todo lo que necesita,", overview_h2_2:"Perfectamente Coordinado",
    ov1_title:"Coordinación Médica", ov1_text:"Análisis experto de su expediente y acceso directo a los mejores especialistas mundiales.", ov1_link:"Descubrir nuestros servicios →",
    ov2_title:"Destinos Principales", ov2_text:"París, Ginebra, Londres, Berlín — las cuatro capitales de la excelencia médica en Europa.", ov2_link:"Ver destinos →",
    ov3_title:"Proceso Sin Fricciones", ov3_text:"Desde el primer contacto hasta la recuperación completa, un conserje dedicado gestiona cada paso.", ov3_link:"Cómo funciona →",
    cta_h2_1:"Su salud no puede esperar.", cta_h2_2:"Nosotros tampoco.",
    cta_p:"Nuestro equipo responde en 48 horas a cada consulta, con discreción absoluta y cuidado profesional.",
    cta_btn:"Solicitar una Consulta Privada",
    gal1:"Hospitalidad VIP", gal2:"París, Francia", gal3:"Excelencia Europea", gal4:"Viaje Privado",
    footer_copy:"© 2025 NobleCare. Todos los derechos reservados.",
    svc_eyebrow:"Nuestros Servicios",
    svc_h1_1:"Una Suite Completa de", svc_h1_2:"Servicios Médicos Premium",
    svc_tag:"Lo Que Ofrecemos",
    svc_h2_1:"Cada Aspecto de Su Viaje,", svc_h2_2:"Perfectamente Gestionado",
    svc_sub:"Desde el primer contacto hasta la recuperación completa, nuestro equipo orquesta cada detalle con precisión y discreción.",
    svc1_title:"Coordinación Médica", svc1_desc:"Análisis experto de su expediente médico y acceso directo a los mejores especialistas mundiales. Identificamos la institución y el experto adecuados para su condición.",
    svc1_l1:"Evaluación integral del expediente médico", svc1_l2:"Identificación del hospital y especialista óptimo", svc1_l3:"Programación de citas prioritarias", svc1_l4:"Oncología, cardiología y enfermedades raras", svc1_l5:"Servicios de segunda opinión", svc1_l6:"Coordinación del plan de tratamiento",
    svc2_title:"Viajes y Logística", svc2_desc:"Arreglos de viaje internacional sin fricciones, incluida la obtención de visa médica, coordinación de aviación privada y alojamiento de primera calidad.",
    svc2_l1:"Obtención de visa médica", svc2_l2:"Coordinación de jet privado y clase ejecutiva", svc2_l3:"Reserva de hotel 5 estrellas y suite hospitalaria", svc2_l4:"Traslados privados al aeropuerto", svc2_l5:"Alojamiento para familiares", svc2_l6:"Planificación del viaje de regreso",
    svc3_title:"Asistencia Personal", svc3_desc:"Un asistente personal dedicado le acompaña durante todo su viaje médico, garantizando una comunicación clara en cada etapa.",
    svc3_l1:"Intérpretes médicos certificados (EN / FR / AR)", svc3_l2:"Asistente personal dedicado 24h", svc3_l3:"Acompañamiento y enlace hospitalario", svc3_l4:"Apoyo administrativo y de documentación", svc3_l5:"Comunicación y actualizaciones familiares", svc3_l6:"Seguimiento post-consulta",
    svc4_title:"Servicios VIP", svc4_desc:"El más alto estándar de atención privada y seguridad para clientes que requieren total discreción y un nivel inigualable de confort personal.",
    svc4_l1:"Seguridad privada", svc4_l2:"Suites hospitalarias premium", svc4_l3:"Chef privado si se requiere", svc4_l4:"Atención postoperatoria de lujo", svc4_l5:"Servicios de conserjería para acompañantes", svc4_l6:"Gestión confidencial de comunicaciones",
    price_tag:"Tarifa de Conserjería", price_h2_1:"Precios Transparentes,", price_h2_2:"Todo Incluido",
    price_label:"Tarifa Base", price_period:"por caso — excluidos costos médicos y de viaje",
    price_desc:"Nuestra tarifa de conserjería cubre el servicio completo de coordinación: análisis del expediente médico, identificación del especialista, programación de citas y gestión logística.",
    price_btn:"Solicitar una Cotización Detallada",
    dest_eyebrow:"Destinos Médicos",
    dest_h1_1:"Las Principales Ciudades", dest_h1_2:"Médicas de Europa",
    dest_tag:"4 Destinos",
    dest_h2_1:"Los Centros Médicos", dest_h2_2:"Más Avanzados del Mundo",
    dest_sub:"Colaboramos exclusivamente con las instituciones mejor clasificadas de Europa, seleccionadas por su excelencia clínica y experiencia con pacientes internacionales.",
    dest_cta_tag:"¿No está seguro del destino?",
    dest_cta_h2_1:"Le Recomendaremos", dest_cta_h2_2:"La Mejor Opción",
    dest_cta_p:"Comparta su situación médica y le identificaremos el hospital y la ciudad más adecuados para su condición.",
    dest_cta_btn:"Obtener una Recomendación",
    proc_eyebrow:"Cómo Funciona",
    proc_h1_1:"Su Viaje en", proc_h1_2:"Cinco Pasos",
    proc_tag:"El Proceso NobleCare",
    proc_h2_1:"Desde el Primer Contacto", proc_h2_2:"hasta la Recuperación Completa",
    proc_sub:"Gestionamos cada aspecto de su viaje médico para que usted y su familia puedan concentrarse en lo más importante — su salud.",
    step1_tag:"Contacto Inicial", step1_title:"Usted Nos Contacta",
    step1_desc:"El proceso comienza en el momento en que nos contacta. Se le asignará un gestor de caso dedicado en 24 horas.",
    step2_tag:"Revisión Médica", step2_title:"Analizamos Su Caso",
    step2_desc:"Su expediente médico es revisado por nuestra red de especialistas asociados. Evaluamos todas las opciones de tratamiento e identificamos la institución más apropiada.",
    step3_tag:"Propuesta Personalizada", step3_title:"Su Plan Completo",
    step3_desc:"Le presentamos un plan completo y detallado que incluye el hospital recomendado, el especialista, la ruta de tratamiento y la estimación de costos.",
    step4_tag:"Organización Total", step4_title:"Nosotros Nos Encargamos de Todo",
    step4_desc:"Con su aprobación, gestionamos toda la operación logística: visa médica, vuelos internacionales, traslados privados y reserva de alojamiento.",
    step5_tag:"Acompañamiento In Situ", step5_title:"Estamos Con Usted",
    step5_desc:"Desde el momento en que aterriza, su conserje personal está a su lado. Le acompañamos en cada cita, traducimos cada consulta y gestionamos cada detalle administrativo.",
    proc_ready_tag:"¿Listo para Comenzar?",
    proc_ready_h2_1:"Inicie Su Viaje", proc_ready_h2_2:"Hoy",
    proc_ready_p:"Envíe su expediente médico de forma segura y reciba su plan de tratamiento personalizado en 48 horas.",
    proc_ready_btn1:"Solicitar una Consulta", proc_ready_btn2:"Ver Nuestros Servicios",
    about_eyebrow:"Sobre NobleCare",
    about_h1_1:"La Confianza de las Familias", about_h1_2:"Más Exigentes del Mundo",
    about_mission_tag:"Nuestra Misión",
    about_mission_h2_1:"Cuando la Salud No Puede Esperar,", about_mission_h2_2:"Cada Detalle Importa",
    about_p1:"NobleCare fue fundado con una convicción simple pero poderosa: el acceso a la mejor atención médica del mundo nunca debería estar limitado por la geografía o la complejidad administrativa.",
    about_pull:"\"Salvamos la distancia entre su familia y los mejores especialistas del planeta.\"",
    about_p2:"Actuamos como un intermediario de confianza — coordinador médico, experto en viajes y asesor personal — guiando a nuestros clientes en cada etapa con precisión y absoluta discreción.",
    about_values_tag:"Nuestros Valores",
    about_values_h2_1:"Los Principios que", about_values_h2_2:"Guían Todo lo que Hacemos",
    val1_title:"Excelencia Sin Compromisos", val1_text:"Colaboramos exclusivamente con instituciones clasificadas entre las mejores del mundo.",
    val2_title:"Confidencialidad Absoluta", val2_text:"Cada caso se maneja bajo estricto acuerdo de no divulgación.",
    val3_title:"Cuidado Humano Genuino", val3_text:"Detrás de cada caso hay una familia ante la incertidumbre. Abordamos a cada cliente con calidez y empatía.",
    testi_tag:"Testimonios de Clientes",
    testi_h2_1:"Las Palabras de Aquellos", testi_h2_2:"a Quienes Hemos Servido",
    contact_eyebrow:"Contáctenos",
    contact_h1_1:"Solicitar una", contact_h1_2:"Consulta Privada",
    contact_tag:"Póngase en Contacto",
    contact_h2_1:"Estamos Aquí", contact_h2_2:"Para Usted",
    contact_p1:"Todas las consultas se manejan con absoluta discreción. Nuestro equipo responderá en 48 horas para discutir su situación.",
    contact_p2:"Ya sea que tenga una necesidad médica urgente o simplemente esté explorando opciones, no hay ninguna obligación. Su primera consulta es completamente confidencial y gratuita.",
    contact_email_label:"Correo Seguro", contact_wa_label:"WhatsApp", contact_phone_label:"Línea Privada",
    form_title:"Solicitud de Consulta Privada",
    form_sub:"Toda la información se trata con estricta confidencialidad.",
    form_lock:"🔒 Sus datos nunca se comparten con terceros.",
    form_fname:"Nombre *", form_lname:"Apellido *",
    form_email:"Dirección de Correo *", form_phone:"Teléfono / WhatsApp",
    form_country:"País de Residencia *", form_country_default:"Seleccione su país",
    form_specialty:"Especialidad Médica Requerida *", form_specialty_default:"Seleccione una especialidad",
    form_dest:"Destino Preferido", form_dest_default:"Sin preferencia — recomiende el mejor",
    form_message:"Breve Descripción",
    form_submit:"Enviar Solicitud de Consulta →",
    blog_eyebrow:"Guías Médicas",
    blog_h1_1:"Guías de Expertos para", blog_h1_2:"Pacientes Internacionales",
    blog_tag:"Todos los Artículos",
    newsletter_h2_1:"Manténgase", newsletter_h2_2:"Informado",
    newsletter_p:"Reciba nuestras guías expertas sobre viajes médicos, atención sanitaria europea y derechos de los pacientes — enviadas discretamente a su bandeja de entrada.",
    newsletter_btn:"Suscribirse",
  },

  pt: {
    nav_home:"Início", nav_services:"Serviços", nav_destinations:"Destinos",
    nav_process:"Processo", nav_about:"Sobre", nav_blog:"Blog", nav_contact:"Contato",
    nav_cta:"Consulta Privada",
    hero_eyebrow:"Concierge Médico Internacional",
    hero_h1_1:"Acesse os Melhores", hero_h1_2:"Especialistas Médicos", hero_h1_3:"do Mundo",
    hero_p:"Conectamos pacientes internacionais distintos às instituições médicas mais avançadas da Europa — gerenciando cada detalhe, desde consultas com especialistas até arranjos de viagem privada.",
    hero_btn:"Solicitar uma Consulta Privada", hero_btn2:"Como funciona",
    badge1:"Confidencialidade Absoluta", badge2:"Suporte Dedicado 24/7", badge3:"Assistência Multilíngue",
    stat1_label:"Tempo médio de resposta", stat2_label:"Instituições parceiras",
    stat3_label:"Destinos médicos", stat4_label:"Serviço confidencial",
    overview_tag:"O Que Oferecemos",
    overview_h2_1:"Tudo o que você precisa,", overview_h2_2:"Perfeitamente Orquestrado",
    ov1_title:"Coordenação Médica", ov1_text:"Análise especializada do seu prontuário e acesso direto aos melhores especialistas mundiais.", ov1_link:"Descubra nossos serviços →",
    ov2_title:"Destinos Principais", ov2_text:"Paris, Genebra, Londres, Berlim — as quatro capitais da excelência médica na Europa.", ov2_link:"Ver destinos →",
    ov3_title:"Processo Fluído", ov3_text:"Do primeiro contato até a recuperação completa, um concierge dedicado gerencia cada etapa.", ov3_link:"Como funciona →",
    cta_h2_1:"Sua saúde não pode esperar.", cta_h2_2:"Nós também não.",
    cta_p:"Nossa equipe responde em 48 horas a cada consulta, com discrição absoluta e cuidado profissional.",
    cta_btn:"Solicitar uma Consulta Privada",
    gal1:"Hospitalidade VIP", gal2:"Paris, França", gal3:"Excelência Europeia", gal4:"Viagem Privada",
    footer_copy:"© 2025 NobleCare. Todos os direitos reservados.",
    svc_eyebrow:"Nossos Serviços",
    svc_h1_1:"Uma Suite Completa de", svc_h1_2:"Serviços Médicos Premium",
    svc_tag:"O Que Oferecemos",
    svc_h2_1:"Cada Aspecto da Sua Jornada,", svc_h2_2:"Perfeitamente Gerenciado",
    svc_sub:"Do primeiro contato até a recuperação completa, nossa equipe orquestra cada detalhe com precisão e discrição.",
    svc1_title:"Coordenação Médica", svc1_desc:"Análise especializada do seu prontuário médico e acesso direto aos melhores especialistas mundiais.",
    svc1_l1:"Avaliação completa do prontuário médico", svc1_l2:"Identificação do hospital e especialista ideal", svc1_l3:"Agendamento prioritário de consultas", svc1_l4:"Oncologia, cardiologia e doenças raras", svc1_l5:"Serviços de segunda opinião", svc1_l6:"Coordenação do plano de tratamento",
    svc2_title:"Viagem e Logística", svc2_desc:"Arranjos de viagem internacional sem complicações, incluindo obtenção de visto médico, coordenação de aviação privada e acomodação premium.",
    svc2_l1:"Obtenção de visto médico", svc2_l2:"Coordenação de jato privado e classe executiva", svc2_l3:"Reserva de hotel 5 estrelas e suíte hospitalar", svc2_l4:"Traslados privados no aeroporto", svc2_l5:"Acomodação para familiares", svc2_l6:"Planejamento da viagem de retorno",
    svc3_title:"Assistência Pessoal", svc3_desc:"Um assistente pessoal dedicado acompanha você durante toda a sua jornada médica, garantindo comunicação clara em cada etapa.",
    svc3_l1:"Intérpretes médicos certificados (EN / FR / AR)", svc3_l2:"Assistente pessoal dedicado 24h", svc3_l3:"Acompanhamento e ligação hospitalar", svc3_l4:"Suporte administrativo", svc3_l5:"Comunicação e atualizações para a família", svc3_l6:"Acompanhamento pós-consulta",
    svc4_title:"Serviços VIP", svc4_desc:"O mais alto padrão de cuidados privados e segurança para clientes que exigem total discrição e um nível incomparável de conforto pessoal.",
    svc4_l1:"Segurança privada", svc4_l2:"Suítes hospitalares premium", svc4_l3:"Chef privado se necessário", svc4_l4:"Cuidados pós-operatórios de luxo", svc4_l5:"Serviços de concierge para acompanhantes", svc4_l6:"Gestão confidencial de comunicações",
    price_tag:"Taxa de Concierge", price_h2_1:"Preços Transparentes,", price_h2_2:"Tudo Incluído",
    price_label:"Taxa Base", price_period:"por caso — excluindo custos médicos e de viagem",
    price_desc:"Nossa taxa de concierge cobre o serviço completo de coordenação: análise do prontuário médico, identificação do especialista, agendamento de consultas e gestão logística.",
    price_btn:"Solicitar um Orçamento Detalhado",
    dest_eyebrow:"Destinos Médicos",
    dest_h1_1:"As Principais Cidades", dest_h1_2:"Médicas da Europa",
    dest_tag:"4 Destinos",
    dest_h2_1:"Os Centros Médicos", dest_h2_2:"Mais Avançados do Mundo",
    dest_sub:"Colaboramos exclusivamente com as instituições mais bem classificadas da Europa, selecionadas pela excelência clínica e experiência com pacientes internacionais.",
    dest_cta_tag:"Não tem certeza do destino?",
    dest_cta_h2_1:"Vamos Recomendar", dest_cta_h2_2:"A Melhor Opção",
    dest_cta_p:"Compartilhe sua situação médica e identificaremos o hospital e a cidade mais adequados para sua condição.",
    dest_cta_btn:"Obter uma Recomendação",
    proc_eyebrow:"Como Funciona",
    proc_h1_1:"Sua Jornada em", proc_h1_2:"Cinco Etapas",
    proc_tag:"O Processo NobleCare",
    proc_h2_1:"Do Primeiro Contato", proc_h2_2:"à Recuperação Completa",
    proc_sub:"Gerenciamos cada aspecto da sua jornada médica para que você e sua família possam se concentrar no que mais importa — sua saúde.",
    step1_tag:"Contato Inicial", step1_title:"Você Nos Contata",
    step1_desc:"O processo começa no momento em que você nos contata. Um gerente de caso dedicado será atribuído a você em 24 horas.",
    step2_tag:"Revisão Médica", step2_title:"Analisamos Seu Caso",
    step2_desc:"Seu prontuário médico é revisado pela nossa rede de especialistas parceiros. Avaliamos todas as opções de tratamento e identificamos a instituição mais adequada.",
    step3_tag:"Proposta Personalizada", step3_title:"Seu Plano Completo",
    step3_desc:"Apresentamos um plano completo e detalhado incluindo o hospital recomendado, o especialista, a rota de tratamento e a estimativa de custos.",
    step4_tag:"Organização Total", step4_title:"Cuidamos de Tudo",
    step4_desc:"Com sua aprovação, gerenciamos toda a operação logística: visto médico, voos internacionais, traslados privados e reserva de acomodação.",
    step5_tag:"Acompanhamento In Loco", step5_title:"Estamos Com Você",
    step5_desc:"Desde o momento em que você aterra, seu concierge pessoal está ao seu lado. Acompanhamos cada consulta, traduzimos cada sessão e gerenciamos cada detalhe administrativo.",
    proc_ready_tag:"Pronto para Começar?",
    proc_ready_h2_1:"Inicie Sua Jornada", proc_ready_h2_2:"Hoje",
    proc_ready_p:"Envie seu prontuário médico com segurança e receba seu plano de tratamento personalizado em 48 horas.",
    proc_ready_btn1:"Solicitar uma Consulta", proc_ready_btn2:"Ver Nossos Serviços",
    about_eyebrow:"Sobre a NobleCare",
    about_h1_1:"A Confiança das Famílias", about_h1_2:"Mais Exigentes do Mundo",
    about_mission_tag:"Nossa Missão",
    about_mission_h2_1:"Quando a Saúde Não Pode Esperar,", about_mission_h2_2:"Cada Detalhe Importa",
    about_p1:"A NobleCare foi fundada com uma convicção simples mas poderosa: o acesso aos melhores cuidados médicos do mundo nunca deve ser limitado pela geografia ou complexidade administrativa.",
    about_pull:"\"Encurtamos a distância entre sua família e os melhores especialistas do planeta.\"",
    about_p2:"Atuamos como um intermediário de confiança — coordenador médico, especialista em viagens e consultor pessoal — guiando nossos clientes em cada etapa com precisão e discrição absoluta.",
    about_values_tag:"Nossos Valores",
    about_values_h2_1:"Os Princípios que", about_values_h2_2:"Guiam Tudo o que Fazemos",
    val1_title:"Excelência Sem Compromissos", val1_text:"Colaboramos exclusivamente com instituições classificadas entre as melhores do mundo.",
    val2_title:"Confidencialidade Absoluta", val2_text:"Cada caso é tratado sob estrito acordo de não divulgação.",
    val3_title:"Cuidado Humano Genuíno", val3_text:"Por trás de cada caso há uma família diante da incerteza. Abordamos cada cliente com calor e empatia.",
    testi_tag:"Depoimentos de Clientes",
    testi_h2_1:"As Palavras Daqueles", testi_h2_2:"que Servimos",
    contact_eyebrow:"Contate-Nos",
    contact_h1_1:"Solicitar uma", contact_h1_2:"Consulta Privada",
    contact_tag:"Entre em Contato",
    contact_h2_1:"Estamos Aqui", contact_h2_2:"Para Você",
    contact_p1:"Todas as consultas são tratadas com absoluta discrição. Nossa equipe responderá em 48 horas para discutir sua situação.",
    contact_p2:"Seja para uma necessidade médica urgente ou para explorar opções, não há nenhuma obrigação. Sua primeira consulta é completamente confidencial e gratuita.",
    contact_email_label:"E-mail Seguro", contact_wa_label:"WhatsApp", contact_phone_label:"Linha Privada",
    form_title:"Solicitação de Consulta Privada",
    form_sub:"Todas as informações são tratadas com estrita confidencialidade.",
    form_lock:"🔒 Seus dados nunca são compartilhados com terceiros.",
    form_fname:"Nome *", form_lname:"Sobrenome *",
    form_email:"Endereço de E-mail *", form_phone:"Telefone / WhatsApp",
    form_country:"País de Residência *", form_country_default:"Selecione seu país",
    form_specialty:"Especialidade Médica Necessária *", form_specialty_default:"Selecione uma especialidade",
    form_dest:"Destino Preferido", form_dest_default:"Sem preferência — recomendar o melhor",
    form_message:"Breve Descrição",
    form_submit:"Enviar Solicitação de Consulta →",
    blog_eyebrow:"Guias Médicos",
    blog_h1_1:"Guias de Especialistas para", blog_h1_2:"Pacientes Internacionais",
    blog_tag:"Todos os Artigos",
    newsletter_h2_1:"Mantenha-se", newsletter_h2_2:"Informado",
    newsletter_p:"Receba nossos guias especializados sobre viagens médicas, saúde europeia e direitos dos pacientes — entregues discretamente na sua caixa de entrada.",
    newsletter_btn:"Inscrever-se",
  }
};

function applyLang(code) {
  var t = LANG[code];
  if (!t) return;
  localStorage.setItem('nc_lang', code);
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.textContent = t[key];
  });
  document.querySelectorAll('.lang-btn').forEach(function(btn) {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === code);
  });
}

function initLang() {
  var saved = localStorage.getItem('nc_lang') || 'en';
  applyLang(saved);
}

document.addEventListener('DOMContentLoaded', initLang);
